# Site settings
title: CHDBOY Support Site
description: Documentation, privacy policy, and support for CHDBOY Android app
baseurl: "/CHDBOY" # the subpath of your site, e.g. /blog
url: "https://izzy2lost.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md

# Include
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Default values
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"